f
<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
                <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-nav-bar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>                
                <a class="nav navbar-brand" href="index.php">
                    Sqwirrel
                </a>
                </div>
            <hr class="hr">
<div class="collapse navbar-collapse" id="collapse-nav-bar">
<div class="navbar-left col-xs-12 col-sm-4 col-md-4 marg-top">
<div class="input-group">
      <input type="text" class="form-control" aria-label="...">
      <div class="input-group-btn">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">meine Anzeigen<span class="caret"></span></button>
        <ul class="dropdown-menu dropdown-menu-right">
          <li><a href="ticket_neu.php">neue Anzeige erstellen</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </div><!-- /btn-group -->
    </div><!-- /input-group -->
   </div>             
   <div class="navbar-right col-xs-12 col-sm-6 col-md-4">
                 <a class="navbar-btn btn btn-warning col-xs-6 col-xs-offset-3 col-sm-6 col-sm-offset-6 col-md-4 col-md-offset-8" id="login_btn" data-toggle="modal" data-target="#userModal" style="font-weight: bold; color: white"><?php echo $textButton; ?></a> 
    </div>
      </div>
     </div>
  </div><!--NAV-->